services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_EXT_TCP_HEARTBEAT_INTERVAL=10000
      - EVENTSTORE_EXT_TCP_HEARTBEAT_TIMEOUT=10000